### ISSUE TITLE
Restore latest Sufia commit

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#201]
Restore 8b9f4b7c5456f423511496489b630a99e7bf0c5c once we've figure out why it's causing problems with uploading. On AIC systems, uploading files produces this error:

``` bash
E, [2016-01-15T22:36:38.127069 #98540] ERROR -- : GenericFilesController::create rescued Redis::CommandError
    ERR unknown command 'script'
 /usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:114:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis.rb:2326:in `block in script'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis.rb:57:in `block in synchronize'
/usr/local/hydra/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis.rb:57:in `synchronize'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis.rb:2325:in `script'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/redlock-0.1.5/lib/redlock/client.rb:121:in `load_scripts'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/redlock-0.1.5/lib/redlock/client.rb:101:in `initialize'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/redlock-0.1.5/lib/redlock/client.rb:23:in `new'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/redlock-0.1.5/lib/redlock/client.rb:23:in `block in initialize'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/redlock-0.1.5/lib/redlock/client.rb:21:in `map'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/redlock-0.1.5/lib/redlock/client.rb:21:in `initialize'
/data/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/bundler/gems/sufia-7d7c7393242f/sufia-models/app/services/sufia/lock_manager.rb:16:in `new'
/data/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/bundler/gems/sufia-7d7c7393242f/sufia-models/app/services/sufia/lock_manager.rb:16:in `initialize'
/data/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/bundler/gems/sufia-7d7c7393242f/sufia-models/app/services/sufia/lockable.rb:10:in `new'
/data/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/bundler/gems/sufia-7d7c7393242f/sufia-models/app/services/sufia/lockable.rb:10:in `lock_manager'
/data/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/bundler/gems/sufia-7d7c7393242f/sufia-models/app/services/sufia/lockable.rb:6:in `acquire_lock_for'
/data/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/bundler/gems/sufia-7d7c7393242f/sufia-models/app/models/batch.rb:15:in `find_or_create'
/data/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/bundler/gems/sufia-7d7c7393242f/app/controllers/concerns/sufia/files_controller_behavior.rb:236:in `process_file'
/data/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/bundler/gems/sufia-7d7c7393242f/app/controllers/concerns/sufia/files_controller_behavior.rb:105:in `create_from_upload'
/data/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/bundler/gems/sufia-7d7c7393242f/app/controllers/concerns/sufia/files_controller_behavior.rb:90:in `create'
/data/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/bundler/gems/sufia-7d7c7393242f/app/controllers/concerns/sufia/files_controller/browse_everything.rb:9:in `create'
/data/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/bundler/gems/sufia-7d7c7393242f/app/controllers/concerns/sufia/files_controller/local_ingest_behavior.rb:9:in `create'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/abstract_controller/base.rb:198:in `process_action'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/rendering.rb:10:in `process_action'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/rescue.rb:29:in `process_action'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/abstract_controller/base.rb:137:in `process'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionview-4.2.4/lib/action_view/rendering.rb:30:in `process'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal.rb:196:in `dispatch'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal.rb:237:in `block in action'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:76:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:45:in `serve'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `each'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `serve'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:821:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/engine.rb:518:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/railtie.rb:194:in `public_send'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/railtie.rb:194:in `method_missing'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:51:in `serve'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `each'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `serve'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:821:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/warden-1.2.4/lib/warden/manager.rb:35:in `block in call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/warden-1.2.4/lib/warden/manager.rb:34:in `catch'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/warden-1.2.4/lib/warden/manager.rb:34:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/flash.rb:260:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/query_cache.rb:36:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/active-fedora-9.7.0/lib/active_fedora/ldp_cache.rb:26:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:38:in `call_app'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `block in call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:26:in `tagged'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `tagged'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/engine.rb:518:in `call'
/usr/local/hydra/lakeshore/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:165:in `call'
/usr/local/hydra/lib/ruby/gems/2.2.0/gems/passenger-5.0.6/lib/phusion_passenger/rack/thread_handler_extension.rb:85:in `process_request'
/usr/local/hydra/lib/ruby/gems/2.2.0/gems/passenger-5.0.6/lib/phusion_passenger/request_handler/thread_handler.rb:155:in `accept_and_process_next_request'
/usr/local/hydra/lib/ruby/gems/2.2.0/gems/passenger-5.0.6/lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/local/hydra/lib/ruby/gems/2.2.0/gems/passenger-5.0.6/lib/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads'
/usr/local/hydra/lib/ruby/gems/2.2.0/gems/passenger-5.0.6/lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
```

**Comment by scossu** [comment]
Shall we skip straight to Sufia 6.6?

**Comment by awead** [comment]
Yes, and with any luck, it won't have the above problem!

**Comment by awead** [comment]
Updating Redis on aicdamsdev01 solved the problem. It was using 2.4.10, but the latest is 3.0.7.
